# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0b\x63ustom_auth\"=\n\x13UserRegisterRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"8\n\x14UserRegisterResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\":\n\x10UserLoginRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"Q\n\x11UserLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"=\n\x14RefreshTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xfb\x01\n\x0b\x41uthService\x12O\n\x08Register\x12 .custom_auth.UserRegisterRequest\x1a!.custom_auth.UserRegisterResponse\x12\x46\n\x05Login\x12\x1d.custom_auth.UserLoginRequest\x1a\x1e.custom_auth.UserLoginResponse\x12S\n\x0cRefreshToken\x12 .custom_auth.RefreshTokenRequest\x1a!.custom_auth.RefreshTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERREGISTERREQUEST']._serialized_start=27
  _globals['_USERREGISTERREQUEST']._serialized_end=88
  _globals['_USERREGISTERRESPONSE']._serialized_start=90
  _globals['_USERREGISTERRESPONSE']._serialized_end=146
  _globals['_USERLOGINREQUEST']._serialized_start=148
  _globals['_USERLOGINREQUEST']._serialized_end=206
  _globals['_USERLOGINRESPONSE']._serialized_start=208
  _globals['_USERLOGINRESPONSE']._serialized_end=289
  _globals['_REFRESHTOKENREQUEST']._serialized_start=291
  _globals['_REFRESHTOKENREQUEST']._serialized_end=335
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=337
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=398
  _globals['_AUTHSERVICE']._serialized_start=401
  _globals['_AUTHSERVICE']._serialized_end=652
# @@protoc_insertion_point(module_scope)
