name: CI Dev

on:
  pull_request:
    branches:
      - main

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r services/auth_service/requirements.txt
    
    - name: Install grpcurl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -LO https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz
        tar -xvzf grpcurl_1.8.7_linux_x86_64.tar.gz
        sudo mv grpcurl /usr/local/bin/

    - name: Start gRPC server
      working-directory: ./services/auth_service/auth_service
      run: |
        python grpc_server.py &
        sleep 5  # Allow time for the gRPC server to start

    - name: Test gRPC server with grpcurl
      run: |
        grpcurl -plaintext 127.0.0.1:50051 list
    
    - name: Lint code with flake8
      run: |
        flake8 .
    
    - name : Run tests
      run: |
        pytest -vv
    
    - name : Build docker image
      working-directory: ./services/auth_service
      run: |
        docker build -t micro_biz_keeper/auth_service_dev  --build-arg DJANGO_ENV=dev .

